services:
  db:
    # FIXME: 15 for now, but it's already EOL.
    # should upgrade this, and propose and upgrade plan for customer
    image: postgres:15-alpine
    container_name: "fau_db"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  # NOTE: remove if not needed
  pgadmin:
    image: dpage/pgadmin4
    container_name: "fau_pgadmin"
    env_file:
      - .env
    volumes:
      - data_pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"

volumes:
  postgres_data:
  data_pgadmin:
