"""add id to records, spiders

Revision ID: 97ece5251480
Revises: e81c775456a5
Create Date: 2026-05-15 22:04:29.885103

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97ece5251480"
down_revision: str | None = "e81c775456a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("records", sa.Column("id", sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("records", "id")
    # ### end Alembic commands ###
