"""add pending registrations table

Revision ID: 3f4b8a9b1d7c
Revises: 97ece5251480
Create Date: 2026-05-28 17:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.sql import func

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f4b8a9b1d7c"
down_revision: str | None = "97ece5251480"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pending_registrations",
        sa.Column("id", sa.BigInteger(), sa.Identity(), primary_key=True),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default="pending", nullable=False
        ),
        sa.Column(
            "created_at", sa.TIMESTAMP(), server_default=func.now(), nullable=False
        ),
        sa.Column("confirmed_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("telegram_username", sa.String(length=255), nullable=True),
        sa.Column("telegram_name", sa.String(length=255), nullable=True),
    )
    op.create_index(
        op.f("ix_pending_registrations_code"),
        "pending_registrations",
        ["code"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_pending_registrations_code"), table_name="pending_registrations"
    )
    op.drop_table("pending_registrations")
    # ### end Alembic commands ###
